# -*- coding: utf-8 -*-
"""task2_unemployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFkW0qHrfvONyiKnv2m1ItK9-1XMOiXa

# **TASK 2: Unemployment Analysis with Python **
"""

# ==========================================
# UNEMPLOYMENT ANALYSIS WITH PYTHON
# ==========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

# ==========================================
# 1. LOAD DATA (WITH FALLBACK)
# ==========================================

try:
    df = pd.read_csv("unemployment_data.csv")  # replace with actual dataset file
    print("Dataset loaded successfully!")

except FileNotFoundError:
    print("Dataset not found! Using synthetic unemployment dataset...")

    dates = pd.date_range(start="2018-01-01", end="2023-12-01", freq="MS")

    np.random.seed(42)

    df = pd.DataFrame({
        "Date": dates,
        "Unemployment_Rate": np.random.uniform(4, 7, len(dates))
    })

    # Simulate COVID spike (2020)
    covid_mask = (df["Date"] >= "2020-03-01") & (df["Date"] <= "2021-06-01")
    df.loc[covid_mask, "Unemployment_Rate"] += np.random.uniform(3, 8, covid_mask.sum())

print(df.head())

# ==========================================
# 2. DATA CLEANING
# ==========================================

df.dropna(inplace=True)

df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values("Date")

# Extract useful time features
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month

# ==========================================
# 3. EXPLORATORY DATA ANALYSIS
# ==========================================

plt.figure(figsize=(12,5))
plt.plot(df["Date"], df["Unemployment_Rate"], color="blue")
plt.title("Unemployment Rate Over Time")
plt.xlabel("Year")
plt.ylabel("Unemployment Rate (%)")
plt.show()

# Yearly trend
plt.figure(figsize=(8,5))
sns.lineplot(data=df, x="Year", y="Unemployment_Rate", estimator="mean", marker="o")
plt.title("Average Unemployment Rate by Year")
plt.show()

# Monthly pattern (seasonality check)
plt.figure(figsize=(8,5))
sns.boxplot(x="Month", y="Unemployment_Rate", data=df)
plt.title("Monthly Unemployment Seasonality")
plt.show()

# ==========================================
# 4. COVID-19 IMPACT ANALYSIS
# ==========================================

covid_period = df[(df["Date"] >= "2020-03-01") & (df["Date"] <= "2021-06-01")]
pre_covid = df[df["Date"] < "2020-03-01"]

print("\n📊 COVID IMPACT ANALYSIS:")
print("Average unemployment (Pre-COVID):", pre_covid["Unemployment_Rate"].mean())
print("Average unemployment (During COVID):", covid_period["Unemployment_Rate"].mean())

# Visualization of COVID impact
plt.figure(figsize=(12,5))
plt.plot(df["Date"], df["Unemployment_Rate"], label="Unemployment Rate")

plt.axvspan("2020-03-01", "2021-06-01", color="red", alpha=0.3, label="COVID Period")

plt.title("COVID-19 Impact on Unemployment Rate")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.legend()
plt.show()

# ==========================================
# 5. INSIGHTS
# ==========================================

print("\n📌 KEY INSIGHTS:")
print("- Unemployment spikes significantly during COVID period")
print("- Post-COVID recovery trend may be visible")
print("- Seasonal fluctuations suggest monthly variation patterns")
print("- Policy intervention needed during crisis periods")